[Interface]
PrivateKey = sCo/4AFi9RMLHGr0yZjdI3Sz4K4TIszwZQN1053Wsmg=
Address = 10.66.66.2/32
DNS = 1.1.1.1, 9.9.9.9

[Peer]
PublicKey = dLnUVbZjNvMYaWA2ZPYoR0wolV6VKHnnUzO/zU44SEM=
Endpoint = 173.178.55.81:443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
